name: Merge Main to Dev

on: 
  workflow_call:
    secrets:
      PR_CREATE_GITHUB_TOKEN:
        required: true

jobs:
  pr-main-to-dev:
    name: Create Main to Dev PR
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # We checkout on base only if merged. Otherwise we keep head. This helps with testing.
        ref: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref || github.event.pull_request.head.ref }}

    - name: Make new branch
      run: |
        git checkout -b feature/from-main-${{ github.sha }}
        git push origin feature/from-main-${{ github.sha }}

    - name: Create PR
      run: |
        cat > pr-body.txt <<EOF
          This PR is to keep main to dev in sync. The PR is created automatically.
          Please make sure to merge this PR (**no squash**).
          Make sure this is a most recent PR if multiple updates to main are done.
          Head branch sha: ${{ github.sha }}
          Last head commit:
          \`\`\`
          $(git log -1 --pretty=format:"%s")
          \`\`\`
        EOF
        gh pr create --title "Main to Dev - ${{ github.event.pull_request.title }}" \
                     --assignee ${{ github.event.pull_request.user.login }} \
                     --base dev \
                     --body-file pr-body.txt
      env:
        GITHUB_TOKEN: ${{ secrets.PR_CREATE_GITHUB_TOKEN }}

    - name: Enable Auto Merge
      if: github.event.pull_request.merged == true
      run: |
         gh pr merge --auto --merge
      env:
        GITHUB_TOKEN: ${{ secrets.PR_CREATE_GITHUB_TOKEN }}
