name: Test

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: go-version
      name: Get node version to use
      run: echo "::set-output name=value::$(grep "^go " go.mod | awk '{print $2}')"

    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Get deps
      run: go mod download

    - name: Test
      run: make test
