name: Test

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: node-version
      name: Get node version to use
      run: echo "::set-output name=node-version::$(cat .nvmrc)"

    - uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.node-version.outputs.node-version }}'
        cache: 'npm'
        cache-dependency-path: package.json
        registry-url: 'https://npm.pkg.github.com'
        scope: '@freshcutgg'

    - run: npm i
      env:
        NODE_AUTH_TOKEN: ${{ secrets.FC_READ_PACKAGES_TOKEN }}

    - run: make lint
    - run: make test
